package update

// UpdatePlan represents the complete set of file update decisions organized
// into four action categories: create, update, skip, and delete.
//
// The plan is generated by analyzing Change Detection results and applying
// user-provided options (Force, RemoveOrphans). Each category contains
// FileDecision structs that provide full context for the action.
//
// UpdatePlan uses value types (not pointers) for its slices to ensure
// predictable behavior and prevent accidental mutation.
//
// Example usage:
//
//	plan, err := planner.Plan(changeResults, profile, options, fs)
//	if err != nil {
//	    return err
//	}
//	fmt.Printf("Files to create: %d\n", len(plan.ToCreate))
//	fmt.Printf("Files to update: %d\n", len(plan.ToUpdate))
//	fmt.Printf("Files to skip: %d\n", len(plan.ToSkip))
//	fmt.Printf("Files to delete: %d\n", len(plan.ToDelete))
type UpdatePlan struct {
	// ToCreate contains decisions for files that should be newly created.
	// These are files with FileStatusNew that don't exist on disk yet.
	// Files in this category are automatically created without user intervention.
	ToCreate []FileDecision

	// ToUpdate contains decisions for files that should be updated.
	// By default, this includes files with FileStatusSourceChanged.
	// When Force is true, this also includes FileStatusUserModified and
	// FileStatusConflict files that would otherwise be skipped.
	ToUpdate []FileDecision

	// ToSkip contains decisions for files that should NOT be modified.
	// By default, this includes FileStatusUserModified and FileStatusConflict files.
	// The Rationale field of each decision explains why the file was skipped
	// and provides guidance on how to proceed (e.g., "use --force to overwrite").
	ToSkip []FileDecision

	// ToDelete contains decisions for files that should be removed.
	// This category is only populated when RemoveOrphans is true.
	// Files in this category have FileStatusRemoved (they exist in the
	// manifest but are no longer part of the current profile).
	ToDelete []FileDecision
}
